create table if not exists public.hanooot_contacts (id uuid primary key default gen_random_uuid(), display_name text not null, preferred_language text default 'en', phone text, created_at timestamptz default now());
create table if not exists public.hanooot_deals (id text primary key, company text not null, contact_name text, stage text not null check (stage in ('enquiry','contacted','sourcing','priced','won','lost')), amount numeric default 0, arabic_note text, created_at timestamptz default now());
create table if not exists public.hanooot_orders (id text primary key, deal_id text references public.hanooot_deals(id), status text not null, total numeric default 0, currency text default 'USD', tax_label text default 'tax pending');
create table if not exists public.hanooot_activity (id uuid primary key default gen_random_uuid(), deal_id text references public.hanooot_deals(id), author text not null, body text not null, mentions text[] default '{}', created_at timestamptz default now());
create table if not exists public.hanooot_files (id uuid primary key default gen_random_uuid(), bucket text not null default 'hanooot-drive', path text not null, module text not null, created_at timestamptz default now());
alter table public.hanooot_contacts enable row level security; alter table public.hanooot_deals enable row level security; alter table public.hanooot_orders enable row level security; alter table public.hanooot_activity enable row level security; alter table public.hanooot_files enable row level security;
create policy "demo read contacts" on public.hanooot_contacts for select using (true); create policy "demo read deals" on public.hanooot_deals for select using (true); create policy "demo read orders" on public.hanooot_orders for select using (true); create policy "demo read activity" on public.hanooot_activity for select using (true); create policy "demo read files" on public.hanooot_files for select using (true);
insert into public.hanooot_deals (id, company, contact_name, stage, amount, arabic_note) values ('CN-7716','Engines World','Yahya Hamadani','priced',150,'يرجى تأكيد السعر قبل الشحن'), ('CN-7810','Mohammed Ghazi','Kitchen supply','sourcing',320,'سعر مستهدف أقل من 9$') on conflict (id) do nothing;
insert into public.hanooot_orders (id, deal_id, status, total, currency, tax_label) values ('HO-1042','CN-7716','Created from Mark Won',150,'USD','IQD VAT ready') on conflict (id) do nothing;
